FROM python:3.10-slim

WORKDIR /app

COPY broker-requirements.txt /app/

RUN pip install -r broker-requirements.txt

COPY message_broker.py chunker.py task.py converter.py /app/

CMD ["python", "message_broker.py"]
# FROM redis:latest

# CMD ["redis-server"]