FROM python:3.10-slim

WORKDIR /app

COPY broker-requirements.txt /app/

RUN pip install -r broker-requirements.txt

COPY message_broker.py chunker.py task.py converter.py /app/

FROM redis:latest

CMD ["redis-server"]