name: Build Broker CI

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  BASE_IMG_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Log in to the container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Derive short SHA name
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Initialize Submodules
      run: git submodule update --init --recursive
    - name: List Submodule Files
      run: ls -R video_processing
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.broker \
        --tag ghcr.io/${{ env.BASE_IMG_NAME }}/toktik-broker:${{ steps.vars.outputs.sha_short }} \
        --tag ghcr.io/${{ env.BASE_IMG_NAME }}/toktik-broker:latest
    - name: Publish the images
      run: | 
        docker push ghcr.io/${{ env.BASE_IMG_NAME }}/toktik-broker:${{ steps.vars.outputs.sha_short }}
        docker push ghcr.io/${{ env.BASE_IMG_NAME }}/toktik-broker:latest